/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    EditorSetting: typeof import('./src/components/EditorSetting.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JsonEditor: typeof import('./src/components/JsonEditor.vue')['default']
    MonacoDiffEditor: typeof import('./src/components/MonacoDiffEditor.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
